name = "mapassign-api"
main = "backend/index.ts"
compatibility_date = "2024-01-01"



[[kv_namespaces]]
binding = "SESSIONS"
# You must create this namespace using: wrangler kv:namespace create SESSIONS
id = "7bfd440028df45759033598e67b28647"

[[d1_databases]]
binding = "DB"
database_name = "mapassign"
# You must create this database using: wrangler d1 create map-assign-db
database_id = "535e995a-3ac8-4cbd-b2f1-0be4fca3c224"
