export function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) {
    return false;
  }
  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return result === 0;
}

export async function hashPassword(password: string, saltHex?: string): Promise<string> {
  const encoder = new TextEncoder();
  const passwordBuffer = encoder.encode(password);

  let salt: Uint8Array;
  if (saltHex) {
    const hexMatch = saltHex.match(/.{1,2}/g);
    if (!hexMatch) throw new Error('Invalid salt hex format');
    salt = new Uint8Array(hexMatch.map(byte => parseInt(byte, 16)));
  } else {
    salt = new Uint8Array(16);
    crypto.getRandomValues(salt);
  }

  const baseKey = await crypto.subtle.importKey(
    'raw',
    passwordBuffer,
    'PBKDF2',
    false,
    ['deriveBits']
  );

  const derivedBits = await crypto.subtle.deriveBits(
    {
      name: 'PBKDF2',
      salt: salt,
      iterations: 100000,
      hash: 'SHA-256'
    },
    baseKey,
    256
  );

  const saltString = Array.from(salt).map(b => b.toString(16).padStart(2, '0')).join('');
  const hashString = Array.from(new Uint8Array(derivedBits)).map(b => b.toString(16).padStart(2, '0')).join('');

  return `${saltString}:${hashString}`;
}

export async function verifyPassword(password: string, storedHashWithSalt: string): Promise<boolean> {
  const parts = storedHashWithSalt.split(':');
  if (parts.length !== 2) {
    return false;
  }
  const [saltHex, storedHash] = parts;
  const inputHashWithSalt = await hashPassword(password, saltHex);
  const inputHash = inputHashWithSalt.split(':')[1];
  return timingSafeEqual(inputHash, storedHash);
}

export async function verifyAdminPassword(password: string, adminPasswordHash: string): Promise<boolean> {
  // adminPasswordHash is stored in secrets as a base64 or hex PBKDF2 hash (created via hash-password.ts)
  // Let's assume the hash format generated by our script is identical: salt:hash
  return verifyPassword(password, adminPasswordHash);
}
