export const COUNTRY_NAMES: Record<string, string> = {
  af: "Afganistan", ax: "Aland Adaları", al: "Arnavutluk", dz: "Cezayir", as: "Amerikan Samoası",
  ad: "Andorra", ao: "Angola", ai: "Anguilla", aq: "Antarktika", ag: "Antigua ve Barbuda",
  ar: "Arjantin", am: "Ermenistan", aw: "Aruba", au: "Avustralya", at: "Avusturya",
  az: "Azerbaycan", bs: "Bahamalar", bh: "Bahreyn", bd: "Bangladeş", bb: "Barbados",
  by: "Belarus", be: "Belçika", bz: "Belize", bj: "Benin", bm: "Bermuda",
  bt: "Butan", bo: "Bolivya", bq: "Karayip Hollandası", ba: "Bosna-Hersek", bw: "Botsvana",
  bv: "Bouvet Adası", br: "Brezilya", io: "Britanya Hint Okyanusu Toprakları", bn: "Brunei", bg: "Bulgaristan",
  bf: "Burkina Faso", bi: "Burundi", cv: "Yeşil Burun Adaları", kh: "Kamboçya", cm: "Kamerun",
  ca: "Kanada", ky: "Cayman Adaları", cf: "Orta Afrika Cumhuriyeti", td: "Çad", cl: "Şili",
  cn: "Çin", cx: "Christmas Adası", cc: "Cocos Adaları", co: "Kolombiya", km: "Komorlar",
  cd: "Kongo Demokratik Cumhuriyeti", cg: "Kongo Cumhuriyeti", ck: "Cook Adaları", cr: "Kosta Rika", ci: "Fildişi Sahili",
  hr: "Hırvatistan", cu: "Küba", cw: "Curaçao", cy: "Kıbrıs", cz: "Çekya",
  dk: "Danimarka", dj: "Cibuti", dm: "Dominika", do: "Dominik Cumhuriyeti", ec: "Ekvador",
  eg: "Mısır", sv: "El Salvador", gq: "Ekvator Ginesi", er: "Eritre", ee: "Estonya",
  sz: "Esvatini", et: "Etiyopya", fk: "Falkland Adaları", fo: "Faroe Adaları", fj: "Fiji",
  fi: "Finlandiya", fr: "Fransa", gf: "Fransız Guyanası", pf: "Fransız Polinezyası", tf: "Fransız Güney Toprakları",
  ga: "Gabon", gm: "Gambiya", ge: "Gürcistan", de: "Almanya", gh: "Gana",
  gi: "Cebelitarık", gr: "Yunanistan", gl: "Grönland", gd: "Grenada", gp: "Guadelup",
  gu: "Guam", gt: "Guatemala", gg: "Guernsey", gn: "Gine", gw: "Gine-Bissau",
  gy: "Guyana", ht: "Haiti", hm: "Heard Adası ve McDonald Adaları", va: "Vatikan", hn: "Honduras",
  hk: "Hong Kong", hu: "Macaristan", is: "İzlanda", in: "Hindistan", id: "Endonezya",
  ir: "İran", iq: "Irak", ie: "İrlanda", im: "Isle of Man", il: "İsrail",
  it: "İtalya", jm: "Jamaika", jp: "Japonya", je: "Jersey", jo: "Ürdün",
  kz: "Kazakistan", ke: "Kenya", ki: "Kiribati", kp: "Kuzey Kore", kr: "Güney Kore",
  kw: "Kuveyt", kg: "Kırgızistan", la: "Laos", lv: "Letonya", lb: "Lübnan",
  ls: "Lesotho", lr: "Liberia", ly: "Libya", li: "Lihtenştayn", lt: "Litvanya",
  lu: "Lüksemburg", mo: "Makao", mg: "Madagaskar", mw: "Malavi", my: "Malezya",
  mv: "Maldivler", ml: "Mali", mt: "Malta", mh: "Marshall Adaları", mq: "Martinik",
  mr: "Moritanya", mu: "Mauritius", yt: "Mayotte", mx: "Meksika", fm: "Micronesia",
  md: "Moldova", mc: "Monako", mn: "Moğolistan", me: "Karadağ", ms: "Montserrat",
  ma: "Fas", mz: "Mozambik", mm: "Myanmar", na: "Namibya", nr: "Nauru",
  np: "Nepal", nl: "Hollanda", nc: "Yeni Kaledonya", nz: "Yeni Zelanda", ni: "Nikaragua",
  ne: "Nijer", ng: "Nijerya", nu: "Niue", nf: "Norfolk Adası", mk: "Kuzey Makedonya",
  mp: "Kuzey Mariana Adaları", no: "Norveç", om: "Umman", pk: "Pakistan", pw: "Palau",
  ps: "Filistin", pa: "Panama", pg: "Papua Yeni Ginesi", py: "Paraguay", pe: "Peru",
  ph: "Filipinler", pn: "Pitcairn Adaları", pl: "Polonya", pt: "Portekiz", pr: "Porto Riko",
  qa: "Katar", re: "Reunion", ro: "Romanya", ru: "Rusya", rw: "Ruanda",
  bl: "Saint Barthelemy", sh: "Saint Helena", kn: "Saint Kitts ve Nevis", lc: "Saint Lucia", mf: "Saint Martin",
  pm: "Saint Pierre ve Miquelon", vc: "Saint Vincent ve Grenadinler", ws: "Samoa", sm: "San Marino", st: "Sao Tome ve Principe",
  sa: "Suudi Arabistan", sn: "Senegal", rs: "Sırbistan", sc: "Seyşeller", sl: "Sierra Leone",
  sg: "Singapur", sx: "Sint Maarten", sk: "Slovakya", si: "Slovenya", sb: "Solomon Adaları",
  so: "Somali", za: "Güney Afrika", gs: "Güney Georgia ve Güney Sandwich Adaları", ss: "Güney Sudan", es: "İspanya",
  lk: "Sri Lanka", sd: "Sudan", sr: "Suriname", sj: "Svalbard ve Jan Mayen", se: "İsveç",
  ch: "İsviçre", sy: "Suriye", tw: "Tayvan", tj: "Tacikistan", tz: "Tanzanya",
  th: "Tayland", tl: "Doğu Timor", tg: "Togo", tk: "Tokelau", to: "Tonga",
  tt: "Trinidad ve Tobago", tn: "Tunus", tr: "Türkiye", tm: "Türkmenistan", tc: "Turks ve Caicos Adaları",
  tv: "Tuvalu", ug: "Uganda", ua: "Ukrayna", ae: "Birleşik Arap Emirlikleri", gb: "Birleşik Krallık",
  um: "Amerika Birleşik Devletleri Küçük Dış Adaları", us: "Amerika Birleşik Devletleri", uy: "Uruguay", uz: "Özbekistan", vu: "Vanuatu",
  ve: "Venezuela", vn: "Vietnam", vg: "Britanya Virjin Adaları", vi: "ABD Virjin Adaları", wf: "Wallis ve Futuna",
  eh: "Batı Sahra", ye: "Yemen", zm: "Zambia", zw: "Zimbabwe",
  xs: "Somaliland", xq: "Kırım",
  xk: "Kosova",
  xc: "Kuzey Kıbrıs",
  "gb-eng": "İngiltere",
  "gb-sct": "İskoçya",
  "gb-wls": "Galler",
  "gb-nir": "Kuzey İrlanda"
};
